apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: logstash-pipelines
data:

  logstash.conf: |
    # Most configuration is taken from the examples at
    # https://www.elastic.co/guide/en/logstash/6.3/logstash-config-for-filebeat-modules.html
    input {
        beats {
            port => 8751
        }
    }

    filter {

    }

    output {
          elasticsearch {
              hosts => ["http://elasticsearch.default.svc.cluster.local:9200"]
              manage_template => false
              index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
          }
    }
